### ISSUE TITLE
Depends on ITKspatialobjects

### ISSUE THREAD

**Issue by dzenanz** [dream3d/DREAM3DReview#19]
This plugin depends on `ITKspatialobjects-5.1.dll`, but that DLL is not copied like the rest of ITK's libraries into the `Bin` folder. `ITKspatialobjects` should probably be added to some list. Maybe [here](https://github.com/dream3d/DREAM3DReview/blob/dbea030a95607627f1a8d78a0faa15a5b73574e0/CMakeLists.txt#L49) or [here](https://github.com/BlueQuartzSoftware/CMP/blob/97993850f58199215650c17f2982f3da16944154/ITKSupport/IncludeITK.cmake#L154)?

**Comment by imikejackson** [comment]
This has been fixed at some point.
